HanbatMarket/urls.py
from django.urls import path
from . import views

app_name = 'hanbat_market'

urlpatterns = [
    path('', views.index, name='index'),
    path('regist/', views.regist, name='regist'),
    path('detail/<int:pk>/', views.detail, name='detail'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('delete/<int:pk>/', views.delete, name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.shortcuts import redirect
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda r: redirect('hanbat_market:index')),
    path('hanket/', include('HanbatMarket.urls')),
    path('accounts/', include('allauth.urls')),
    
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # media 경로 추가

HanbatMarket/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from HanbatMarket.models import User

class Board(models.Model): #Book Table
    title = models.CharField(max_length=200, verbose_name='상품명', help_text='* 책 제목은 정확하게 기입해주세요.')
    author = models.CharField(max_length=100, verbose_name='저자')
    seller = models.ForeignKey(User, on_delete=models.CASCADE) # on_delete : User가 delete 될 때 게시글을 어떻게 설정한 것인지에 대해 설정 1. 게시글 같이 지우기(CASCADE) 2. 없는 값으로 해서 게시글은 남겨두기
    publisher = models.CharField(max_length=100, verbose_name='출판사')
    minPrice = models.IntegerField(verbose_name='최소구매가')
    maxPrice = models.IntegerField(verbose_name='최대구매가')
    kakaoId = models.CharField(max_length=100, verbose_name='판매자의 kakaoId 또는 전화번호', help_text='* 구매자와의 연락을 위한 정보를 기입해주세요.')
    imgfile = models.ImageField(null=True, upload_to="", blank=True,verbose_name='상품 사진') # 이미지 컬럼 추가
    content = models.TextField(verbose_name='상품 설명')
    published_date = models.DateTimeField(auto_now=True, verbose_name='등록(수정)일')
    under_line = models.BooleanField(verbose_name='밑줄 유무')
    written = models.BooleanField(verbose_name='필기 유무')
    page_named = models.BooleanField(verbose_name='이름 기입')
    page_age = models.BooleanField(verbose_name='페이지 변색')
    ripped = models.BooleanField(verbose_name='페이지 훼손')
    

    def __str__(self):
        return self.title
    
    

HanbatMarket/forms.py
from django import forms
from django.forms import widgets
from .models import Board


class RegistForm(forms.ModelForm):
    class Meta:
        
        model = Board
        image = forms.ImageField()

        
        fields = ['title', 'author','publisher','minPrice','maxPrice','kakaoId','imgfile','content','under_line','written','page_named','page_age','ripped']  # '__all__'
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'author': forms.TextInput(attrs={'class': 'form-control'}),
            'publisher': forms.TextInput(attrs={'class': 'form-control'}),
            'minPrice' : forms.TextInput(attrs={'class': 'form-control'}),
            'maxPrice' : forms.TextInput(attrs={'class': 'form-control'}),
            'kakaoId' : forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
            'under_line': forms.CheckboxInput(),
            'written' : forms.CheckboxInput(),
            'page_named': forms.CheckboxInput(),
            'page_age': forms.CheckboxInput(),
            'ripped': forms.CheckboxInput(),
            
            
        }
        

HanbatMarket/views.py
from HanbatMarket.models import Board
from django.shortcuts import render,redirect
from .models import Board
from .forms import RegistForm
from django.shortcuts import render, redirect, get_object_or_404
from django.core.paginator import Paginator
from django.db.models import Q, Count


def index(request):
    page = request.GET.get('page', '1')  # 페이지 파라미터 얻기, 없으면 1
    board_list = Board.objects.order_by('minPrice')
    search = request.GET.get('search','')
    if search:
      board_list = board_list.filter(
      Q(title__icontains = search) | #제목
      Q(author__icontains = search) #글쓴이
    )
    # 페이징 처리
    paginator = Paginator(board_list, 9)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)  # page에 해당하는 페이징 객체 생성

    context = {'board_list': page_obj,'search':search}   # 페이징 객체(page_obj) 전달
    return render(request, 'HanbatMarket/index.html', context)

def regist(request):
    if request.method == 'POST':
        form = RegistForm(request.POST,request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.seller = request.user  # 현재 로그인한 사용자를 seller로 고정시켜줘야함
            post.save()
            return redirect('hanbat_market:index')
    else:
        form = RegistForm()
    context = {'form': form,}
    return render(request, 'HanbatMarket/regist_form.html', context)


def detail(request, pk):
    board_list = get_object_or_404(Board, id=pk)
    context = {'board_list': board_list}
    return render(request, 'HanbatMarket/detail.html', context)

def edit(request, pk):
    post = get_object_or_404(Board, id=pk)
    if request.method == 'POST':
        form = RegistForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save()
            return redirect('hanbat_market:index')
    else:
        form = RegistForm(instance=post)
    context = {'form': form,}
    return render(request, 'HanbatMarket/edit_form.html', context)

def delete(request, pk):
    post = get_object_or_404(Board, id=pk)
    post.delete()
    return redirect('hanbat_market:index')

HanbatMarket/templates/HanbatMarket/book_info.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row pt-4 my-3">
        <div class="col-md-12">
            <h3>글 등록</h3>
        </div>
    </div>
    <div class="row my-3"></div>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div style="padding: 5px 50px; float:right;">
                <input class="btn btn-primary" type="submit" value="글 등록">
                <a href="#" class="btn btn-primary">글 목록</a>
            </div>
        </form>
    </div>
</div>

{% endblock %}

HanbatMarket/templates/HanbatMarket/detail.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row pt-4 my-3">
        <div class="col-md-12">
            <h3>글 세부 내용</h3>
        </div>
    </div>
    <div class="row my-3">
        <div>
        <div>[책 제목] : {{ board_list.title }}</div>
        <div>[저자] : {{ board_list.author }}</div>
        <div>[출판사] : {{board_list.publisher}}</div>
        <div>[판매자] : {{ board_list.seller}}</div>
        <div>[판매자 카카오톡ID] : {{ board_list.kakaoId}}</div>
        <div>[최대구매가] :{{board_list.minPrice}}</div>
        <div>[최대구매가] :{{board_list.maxPrice}}</div>
        <div>[상품 사진] </div>
        <img src="{{ board_list.imgfile.url }}" width="500">
        </div>
        <table class="table table-bordered">
        
        <td>
                    <p>[상품 설명]</p>
                    {{ board_list.content|linebreaks }}
                    <p><small style="color:silver;text-align:right;">[{{ board_list.published_date|date:"Y-m-d H:i:s" }}]</small></p>
                <text>
                </td>
                </table>
                
  
            <p>밑줄 유무:   
                {% if board_list.under_line %}
                O
                {% else %}
                X
                {% endif %}
            </p>
            <p>필기 유무:   
                {% if board_list.written %}
                O
                {% else %}
                X
                {% endif %}
            </p>
            <p> 이름 기입:   
                {% if board_list.page_named %}
                O
                {% else %}
                X
                {% endif %}
            </p>
            <p> 페이지 변색:   
                {% if board_list.page_age %}
                O
                {% else %}
                X
                {% endif %}
            </p>
            <p> 페이지 훼손:   
                {% if board_list.ripped %}
                O
                {% else %}
                X
                {% endif %}
            
        
    </div>
    <div style="padding: 2px 20px; float:right;">
        <a href="{% url 'hanbat_market:index' %}" class="btn btn-primary">글 목록</a>
    </div>
</div>

{% endblock %}

HanbatMarket/templates/HanbatMarket/edit_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row pt-4 my-3">
        <div class="col-md-12">
            <h3>글 수정</h3>
        </div>
    </div>
    <div class="row my-3"></div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <div style="padding: 5px 50px; float:right;">
                <input class="btn btn-primary" type="submit" value="글 수정">
                <a href="{% url 'hanbat_market:index' %}" class="btn btn-primary">글 목록</a>
            </div>
        </form>
    </div>
</div>

{% endblock %}

HanbatMarket/templates/HanbatMarket/index.html
{% extends 'base.html' %}
{% block content %}
        <!-- Header-->
        <header class="bg-dark py-5">
            <div class="container px-4 px-lg-5 my-5">
                <div class="text-center text-white">
                    <h1 class="display-4 fw-bolder">Hanbat-Market</h1>
                    <p class="lead fw-normal text-white-50 mb-0">Hanbat-National-University-Like-Lion-11th</p>
                </div>
            </div>
        </header>
        <!-- Section-->
        <section class="py-5">
            <form method="GET" action="">
                <div style="text-align: center;" id="search">
                    <input name="search" type="text">
                    <button class="btn btn-secondary"  type="submit">FIND</button>
                  </div>
            </form>  
            <div class="container px-4 px-lg-5 mt-5">
                
                <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                    
                    {% for post in board_list %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            {% if post.imgfile %}
                            <img class="card-img-top" src="{{ post.imgfile.url }}" alt="..." style="width:100%; height:70%">
                            {% else %}
                            <img class="card-img-top" src="x" alt="이미지 없음" style="width:100%; height:70%">
                            {% endif%}
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ post.title }}</h5>
                                    <h6>{{ post.author }}</h6>
                                    <h6>{{ post.publisher }}</h6>
                                    <!-- Product price-->
                                    {{post.minPrice}}원 ~ {{ post.maxPrice }}원
                                    
                                    
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'hanbat_market:detail' post.id %}">상품 상세보기</a></div>
                                <br>
                                <p class="text-center">{{ post.published_date|date:"Y-m-d" }}</p>
                                <p class="text-center">
                                {% if post.seller == user%} 
                                <a href="{% url 'hanbat_market:edit' post.id %}" class="btn btn-outline-info btn-sm">수정</a> 
                                <a href="{% url 'hanbat_market:delete' post.id %}" onclick="if(!confirm('정말 삭제하시겠습니까?')){return false;}" 
                                class="btn btn-outline-danger btn-sm">삭제</a>
                                {%else%}

                                {% endif %}
                                </p>
                                
                            </div>
                        </div>
                    </div>
                    {% endfor %}

 
                </div>
            </div>
            <div style="text-align:center">
            {% if user.is_authenticated %}
            <a href="{% url 'hanbat_market:regist' %}" class="btn btn-outline-secondary">글 등록</a>
            {% else %}
            
            {% endif %} 
            </div>
                <!-- 페이징 처리 -->
    <div class="row my-3">
        <div class="col-md-12 text-center">
            {% if board_list.has_previous %}
                <a href="?page=1">처음</a>
                <a href="?page={{ board_list.previous_page_number }}">이전</a>
            {% endif %}
                <!-- 페이지리스트 -->
                <span style="color:red;font-weight:bold;">{{ board_list.number }}</span> 
                <span> / </span>
                <span style="font-weight:bold;">{{ board_list.paginator.num_pages }}</span>
            {% if board_list.has_next %}
                <a href="?page={{ board_list.next_page_number }}">다음</a>
                <a href="?page={{ board_list.paginator.num_pages }}">끝</a>
            {% endif %}          


        </div>
    </div>
        </section>
        {% endblock %}

HanbatMarket/templates/HanbatMarket/regist_form.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <div class="row pt-4 my-3">
        <div class="col-md-12">
            <h3>글 등록</h3>
        </div>
    </div>
    <div class="row my-3"></div>
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <div style="padding: 5px 50px; float:right;">
                <input class="btn btn-primary" type="submit" value="글 등록">
                <a href="{% url 'hanbat_market:index' %}" class="btn btn-primary">글 목록</a>
            </div>
        </form>
    </div>
</div>

{% endblock %}

HanbatMarket/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        {% load static %}
        <title>Hanbat-Market</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'hanbat_logo.png'%}" />
        <!-- Bootstrap icons-->
        <link rel="stylesheet" href="{% static 'styles.css'%}">    

        <script src="{% static '/js/base.js' %}"></script>
    </head>
    <body>
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container px-4 px-lg-5">
                <a class="navbar-brand" href="{% url 'hanbat_market:index' %}">Hanbat-Market<img id="logo_img" style="width:10%;" src="{% static 'hanbat_logo.png'%}" alt="HBNU_Logo"></a>
                

                    {% if user.is_authenticated %}
                    <p>안녕하세요, {{user}}님!
                        <a href="{% url 'account_logout' %}">로그아웃</a></p>
                        {% else %}
                        <i class="bi-cart-fill me-1"></i>

                    {% load socialaccount %}

                    <button class="btn btn-outline-warning"  type="button" onclick="location.href = '{% provider_login_url 'kakao' %}'">카카오 로그인</button>
                    {% endif %}
                
                <!--<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                 
                        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'hanbat_market:index' %}">Home</a></li>
                        
                    </ul>
                </div>
            -->
                
            </div>
            
        </nav>

        {% block content %}

        {% endblock %}

                <!-- Footer-->
                <footer class="py-5 bg-dark">
                    <div class="container"><p class="m-0 text-center text-white">jckim2 &copy; Hanbat-Market 2023</p></div>
                </footer>
                <!-- Bootstrap core JS-->
                <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
                <!-- Core theme JS-->
                <script src="js/scripts.js"></script>
            </body>
        </html>
        

HanbatMarket/templates/index.html
<!Doctype html>
<html>

<head>
    <meta charset="UTF-8">
    <title>Hanbat-Market</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'index.css'%}">    
</head>

<body>
    <header>
        <div id="logo">Hanbat-Market
            <img id="logo_img" src="hanbat_logo.png" alt="HBNU_Logo">
        </div>
        </div>
        <div id="login">로그인</div>
    </header>
    <main>
        <div>
            <div id="db_table">
                <table>
                    <thead>
                        <th>No</th>
                        <th>상품명</th>
                        <th>
                        <th>책 정보</th>
                        <th>최소 입찰가</th>
                        <th>즉시 구매가</th>
                        <th>남은 시간</th>
                        <th>입찰/구매</th>
                    </thead>
                    <!-- tbody 부분에 DB에서 가져온 정보를 출력?? -->
                    <tbody>
                        <tr>
                            <td id="num">1</td>
                            <td id="book_name"> </td>
                            <td id="book_info"><button><a href="">책 정보</a></button></td> <!-- 여기는 책 정보 나오게 링크를 ? -->
                            <td id="min_price"> </td>
                            <td id="max_price"> </td>
                            <td id="time"> </td>
                            <td id="buy_button"><button><a href="#">입찰/구매</a></button></td>
                        </tr>
                        <tr>
                            <td id="num">2</td>
                            <td id="book_name"> </td>
                            <td id="book_info"><button><a href="">책 정보</a></button></td>
                            <td id="min_price"> </td>
                            <td id="max_price"> </td>
                            <td id="time"> </td>
                            <td id="buy_button"><button><a href="#">입찰/구매</a></button></td>
                        </tr>
                        <tr>
                            <td id="num">3</td>
                            <td id="book_name"> </td>
                            <td id="book_info"><button><a href="">책 정보</a></button></td>
                            <td id="min_price"> </td>
                            <td id="max_price"> </td>
                            <td id="time"> </td>
                            <td id="buy_button"><button><a href="#">입찰/구매</a></button></td>
                        </tr>
                        <tr>
                            <td id="num">4</td>
                            <td id="book_name"> </td>
                            <td id="book_info"><button><a href="">책 정보</a></button></td>
                            <td id="min_price"> </td>
                            <td id="max_price"> </td>
                            <td id="time"> </td>
                            <td id="buy_button"><button><a href="#">입찰/구매</a></button></td>
                        </tr>
                        <tr>
                            <td id="num">5</td>
                            <td id="book_name"> </td>
                            <td id="book_info"><button><a href="">책 정보</a></button></td>
                            <td id="min_price"> </td>
                            <td id="max_price"> </td>
                            <td id="time"> </td>
                            <td id="buy_button"><button><a href="#">입찰/구매</a></button></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div id="under_table">
                <button><a href="./book_info.html" target="_self">등록하기</a></button>
                <div id="search_button"><input type="text"><button>검색</button></div>
            </div>

            <!-- <div id="list">
                <div id="list_prev"> &lt;이전&gt; </div>
                <div id="list_no"><span>1 </span><span>2 </span><span>3 </span><span>4 </span><span>5 </span></div>
                <div id="list_next"> &lt;다음&gt; </div>
            </div> -->
        </div>
    </main>
    <footer></footer>
</body>

</html>